Repository nextcloud/call_summary_bot, pull requests merged in 2023-12, with the labels that each got.

#28 chore(CI): Update workflows
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review

#32 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#33 fix(OCC): Fix deleting secrets
  lib/Command/DeleteSecret.php
Labels: 3. to review, bug

#34 feat(occ): Add a command to repair the bot installation on the local …
  CHANGELOG.md
  appinfo/info.xml
  composer.json
  lib/Command/DeleteSecret.php
  lib/Command/Repair.php
  lib/Migration/InstallBot.php
  lib/Migration/UninstallBot.php
  lib/Service/BotService.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review, enhancement
