Repository nextcloud/call_summary_bot, pull requests merged in 2023-10, with the labels that each got.

#21 Don't use a "weird" title for one-to-one conversations
  lib/Service/SummaryService.php
  tests/Service/SummaryServiceTest.php
Labels: 3. to review, bug

#24 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#23 Bump version to a stable one
  appinfo/info.xml
Labels: 3. to review
