Repository nextcloud/call_summary_bot, pull requests merged in 2024-10, with the labels that each got.

#91 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#92 fix(ci): Add rector and move to vendor-bin
  .github/dependabot.yml
  .github/workflows/phpunit-mysql.yml
  .gitignore
  .php-cs-fixer.dist.php
  Makefile
  composer.json
  composer.lock
  lib/Controller/BotController.php
  lib/Service/BotService.php
  rector.php
  tests/Service/SummaryServiceTest.php
  tests/bootstrap.php
  tests/phpunit.xml
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
Labels: 3. to review, technical debt

#93 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#95 ci: Fix prod installations
  composer.json
Labels: 3. to review, bug

#94 feat(emails): Support email guests
  lib/Controller/BotController.php
Labels: 3. to review, enhancement
