Repository nextcloud/call_summary_bot, pull requests merged in 2024-07, with the labels that each got.

#73 feat(todos): Support solved todos
  lib/Model/LogEntry.php
  lib/Service/SummaryService.php
  tests/Service/SummaryServiceTest.php
Labels: 3. to review, enhancement

#74 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, automated, dependencies

#75 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
