Repository nextcloud/call_summary_bot, pull requests merged in 2025-08, with the labels that each got.

#163 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#169 fix(summary): Skip empty summaries in 1-1
  lib/Service/SummaryService.php
Labels: 3. to review, enhancement

#170 fix(agenda): List author of agenda points
  lib/Listener/BotInvokeListener.php
  lib/Service/SummaryService.php
Labels: 3. to review, bug
